/*++
Copyright (c) 2026 EDR Contributors

Module Name:
    restore.c

Abstract:
    System restore subsystem for the EDR kernel driver.

    Activation uses HMAC-SHA256: the vendor-keygen tool embeds a 256-bit
    activation key into the driver binary.  The agent sends
    HMAC-SHA256(message = license_payload, key = embedded_key) via IOCTL.
    The driver verifies the HMAC and enables the restore feature.

    This is NOT a licensing boundary — it is a "verified intent" gate.
    The Ed25519 license signature is verified in user-mode by the agent
    (shared/src/license.rs).  The driver simply checks that the activation
    came from official software that holds the symmetric activation key.

--*/

#include "restore.h"
#include <bcrypt.h>
#include <ntstatus.h>

#pragma alloc_text(PAGE, EdrIoctlRestoreActivate)
#pragma alloc_text(PAGE, EdrIoctlRestoreDeactivate)
#pragma alloc_text(PAGE, EdrIoctlRestoreStatus)
#pragma alloc_text(PAGE, EdrIoctlRestoreClaimPartition)

//
// ─── HMAC activation key ─────────────────────────────────────────────────────
// Generated by vendor-keygen.  Embedded in the driver binary.
// The corresponding SHA-256 hash of this key is stored in the license payload
// as "restore_key_hash" so the agent can verify it has the correct key.
//

static const UCHAR EdrRestoreHmacKey[32] = {
    0xc8, 0xb8, 0xcf, 0x9d, 0x89, 0x4d, 0x3c, 0x24,
    0x4c, 0x4a, 0x7b, 0x24, 0xdf, 0x4e, 0x5a, 0x7c,
    0x36, 0x55, 0x9f, 0xc9, 0x75, 0x75, 0xde, 0x24,
    0x61, 0x7c, 0x93, 0x85, 0x0c, 0x8c, 0x2e, 0xff
};

//
// ─── IOCTL handlers ──────────────────────────────────────────────────────────
//

NTSTATUS
EdrIoctlRestoreActivate(
    _In_ WDFREQUEST Request,
    _In_ PEDR_DEVICE_CONTEXT Context,
    _In_ size_t InputBufferLength
)
{
    PAGED_CODE();

    // Input format:
    //   [u32 payload_length]  — length of license payload JSON in bytes
    //   [payload_bytes]       — the raw license payload JSON
    //   [u32 hmac_length]     — must be 32
    //   [hmac_bytes]          — HMAC-SHA256(payload, EdrRestoreHmacKey)

    if (InputBufferLength < 4 + 4 + 32) {
        return STATUS_BUFFER_TOO_SMALL;
    }

    PVOID input;
    NTSTATUS status = WdfRequestRetrieveInputBuffer(Request, InputBufferLength, &input, NULL);
    if (!NT_SUCCESS(status)) return status;

    ULONG payloadLen = *(ULONG*)input;
    if (payloadLen == 0 || payloadLen > EDR_RESTORE_MAX_PAYLOAD_SIZE) {
        return STATUS_INVALID_PARAMETER;
    }
    if (InputBufferLength < 4 + payloadLen + 4 + 32) {
        return STATUS_BUFFER_TOO_SMALL;
    }

    UCHAR* payload = (UCHAR*)input + 4;
    UCHAR* hmacField = payload + payloadLen;
    ULONG hmacLen = *(ULONG*)hmacField;
    if (hmacLen != 32) {
        return STATUS_INVALID_PARAMETER;
    }
    UCHAR* hmacReceived = hmacField + 4;

    // Compute HMAC-SHA256(payload) with the embedded key
    BCRYPT_ALG_HANDLE hAlg = NULL;
    UCHAR hmacComputed[32];
    ULONG hmacResultLen = 0;

    status = BCryptOpenAlgorithmProvider(&hAlg, BCRYPT_SHA256_ALGORITHM, NULL, BCRYPT_ALG_HANDLE_HMAC_FLAG);
    if (!NT_SUCCESS(status)) {
        return STATUS_NOT_SUPPORTED;
    }

    // (No chaining mode — SHA256 is a hash, not a cipher)

    // BCryptHash does not support HMAC directly on all builds.
    // Use BCryptCreateHash + BCryptHashData + BCryptFinishHash instead.
    BCRYPT_HASH_HANDLE hHash = NULL;
    status = BCryptCreateHash(hAlg, &hHash, NULL, 0, (PUCHAR)EdrRestoreHmacKey, sizeof(EdrRestoreHmacKey), 0);
    if (!NT_SUCCESS(status)) {
        BCryptCloseAlgorithmProvider(hAlg, 0);
        return status;
    }

    status = BCryptHashData(hHash, payload, payloadLen, 0);
    if (!NT_SUCCESS(status)) {
        BCryptDestroyHash(hHash);
        BCryptCloseAlgorithmProvider(hAlg, 0);
        return status;
    }

    status = BCryptFinishHash(hHash, hmacComputed, sizeof(hmacComputed), 0);
    BCryptDestroyHash(hHash);
    BCryptCloseAlgorithmProvider(hAlg, 0);

    if (!NT_SUCCESS(status)) {
        return status;
    }

    // Compare HMAC
    if (!RtlEqualMemory(hmacReceived, hmacComputed, 32)) {
        KdPrint(("[EDR] Restore activation: HMAC mismatch\n"));
        return STATUS_ACCESS_DENIED;
    }

    // Compute SHA-256 of payload for audit
    BCRYPT_ALG_HANDLE hSha256 = NULL;
    if (NT_SUCCESS(BCryptOpenAlgorithmProvider(&hSha256, BCRYPT_SHA256_ALGORITHM, NULL, 0))) {
        BCryptHash(hSha256, NULL, 0, payload, payloadLen, Context->RestorePayloadHash, 32);
        BCryptCloseAlgorithmProvider(hSha256, 0);
    } else {
        RtlZeroMemory(Context->RestorePayloadHash, 32);
    }

    Context->RestoreActivated = TRUE;
    KdPrint(("[EDR] Restore feature activated\n"));
    return STATUS_SUCCESS;
}

NTSTATUS
EdrIoctlRestoreDeactivate(
    _In_ WDFREQUEST Request,
    _In_ PEDR_DEVICE_CONTEXT Context
)
{
    PAGED_CODE();
    Context->RestoreActivated = FALSE;
    RtlZeroMemory(Context->RestorePayloadHash, 32);
    KdPrint(("[EDR] Restore feature deactivated\n"));
    return STATUS_SUCCESS;
}

NTSTATUS
EdrIoctlRestoreStatus(
    _In_ WDFREQUEST Request,
    _In_ PEDR_DEVICE_CONTEXT Context,
    _In_ size_t OutputBufferLength,
    _Out_ size_t* BytesReturned
)
{
    PAGED_CODE();

    if (OutputBufferLength < sizeof(EDR_RESTORE_STATUS)) {
        return STATUS_BUFFER_TOO_SMALL;
    }

    PEDR_RESTORE_STATUS output;
    NTSTATUS status = WdfRequestRetrieveOutputBuffer(Request, OutputBufferLength, (PVOID*)&output, NULL);
    if (!NT_SUCCESS(status)) return status;

    output->Activated = Context->RestoreActivated;
    RtlCopyMemory(output->PayloadHash, Context->RestorePayloadHash, 32);
    RtlZeroMemory(output->ClaimedPartitionPath, sizeof(output->ClaimedPartitionPath));
    if (Context->RestorePartitionPath.Buffer != NULL) {
        ULONG copyLen = Context->RestorePartitionPath.Length;
        if (copyLen > sizeof(output->ClaimedPartitionPath) - 2) {
            copyLen = sizeof(output->ClaimedPartitionPath) - 2;
        }
        RtlCopyMemory(output->ClaimedPartitionPath, Context->RestorePartitionPath.Buffer, copyLen);
    }
    output->PartitionSize = Context->RestorePartitionSize;

    *BytesReturned = sizeof(EDR_RESTORE_STATUS);
    return STATUS_SUCCESS;
}

NTSTATUS
EdrIoctlRestoreClaimPartition(
    _In_ WDFREQUEST Request,
    _In_ PEDR_DEVICE_CONTEXT Context,
    _In_ size_t InputBufferLength
)
{
    PAGED_CODE();

    if (!Context->RestoreActivated) {
        return STATUS_ACCESS_DENIED;
    }

    // Only the registered agent can claim a partition
    PEPROCESS caller = PsGetCurrentProcess();
    if (caller != Context->AgentProcess) {
        return STATUS_ACCESS_DENIED;
    }

    if (InputBufferLength < sizeof(EDR_RESTORE_CLAIM_INPUT)) {
        return STATUS_BUFFER_TOO_SMALL;
    }

    PEDR_RESTORE_CLAIM_INPUT input;
    NTSTATUS status = WdfRequestRetrieveInputBuffer(Request, InputBufferLength, (PVOID*)&input, NULL);
    if (!NT_SUCCESS(status)) return status;

    // Build device path: \Device\Harddisk%u\Partition%u
    WCHAR path[128];
    NTSTATUS hr = (NTSTATUS)RtlStringCbPrintfW(path, sizeof(path), L"\\Device\\Harddisk%lu\\Partition%lu",
                                     input->PhysicalDriveNumber, input->PartitionNumber);
    if (!NT_SUCCESS(hr)) {
        return STATUS_INVALID_PARAMETER;
    }
    ULONG pathLen = (ULONG)wcslen(path);

    // Store the partition path in device context
    if (Context->RestorePartitionPath.Buffer != NULL) {
        ExFreePoolWithTag(Context->RestorePartitionPath.Buffer, 'RDE ');
    }
    Context->RestorePartitionPath.Buffer = (PWCH)ExAllocatePool2(
        POOL_FLAG_NON_PAGED, (pathLen + 1) * sizeof(WCHAR), 'RDE ');
    if (Context->RestorePartitionPath.Buffer == NULL) {
        return STATUS_INSUFFICIENT_RESOURCES;
    }
    RtlCopyMemory(Context->RestorePartitionPath.Buffer, path, (pathLen + 1) * sizeof(WCHAR));
    Context->RestorePartitionPath.Length = (USHORT)(pathLen * sizeof(WCHAR));
    Context->RestorePartitionPath.MaximumLength = (USHORT)((pathLen + 1) * sizeof(WCHAR));

    // TODO: Open the partition device to verify it exists and collect size info.
    // Requires IoGetDeviceObjectPointer + IRP_MJ_QUERY_INFORMATION.
    Context->RestorePartitionSize = 0;

    KdPrint(("[EDR] Claimed partition: %ws\n", path));
    return STATUS_SUCCESS;
}
